TASKS = {
    "window-open-v2-goal-hidden": "push and open a window",
    "window-close-v2-goal-hidden": "push and close a window", 
    "button-press-topdown-v2-goal-hidden": "press a button from the top",
    "door-open-v2-goal-hidden": "open a door with a revolving joint",
    "drawer-close-v2-goal-hidden": "push and close a drawer",
    "drawer-open-v2-goal-hidden": "open a drawer",
    "push-v2-goal-hidden": "push the puck to a goal",
    "reach-v2-goal-hidden": "reach a goal position",
    "window-open-v2-goal-observable": "push and open a window",
    "window-close-v2-goal-observable": "push and close a window",
    "button-press-topdown-v2-goal-observable": "press a button from the top",
    "door-open-v2-goal-observable": "open a door with a revolving joint",
    "drawer-close-v2-goal-observable": "push and close a drawer",
    "drawer-open-v2-goal-observable": "open a drawer",
    "push-v2-goal-observable": "push the puck to a goal",
    "reach-v2-goal-observable": "reach a goal position",
    "pick-place-v2-goal-observable": "pick and place a puck to a goal",
    "peg-insert-side-v2-goal-observable": "insert a peg sideways",
    # mujoco
    "h1hand-run-customized-v0": "a humanoid robot running",
    "h1hand-sit_hard-customized-v0": "a humanoid robot sitting on a chair",
    "h1hand-powerlift-customized-v0": "a humanoid robot performs clean and jerk",
    "h1hand-balance_hard-customized-v0": "a humanoid robot balancing on the board",
    "h1hand-crawl-customized-v0": "a humanoid robot crawling",
    "h1hand-push-customized-v0": "a humanoid robot pushing a box to the target",
    "h1hand-reach-customized-v0": "a humanoid robot reaching the 3D point with the left hand",
    "CustomizedHumanoid-v4": "a humanoid robot running",
    "h1hand_basketball-customized-v0": "a humanoid robot throwing a ball into the basket",
    "h1hand-cabinet-customized-v0": "a humanoid robot opening a cabinet door and putting a cube inside",
    "h1hand-slide-customized-v0": "a humanoid robot walking",
    "h1hand-stair-customized-v0": "a humanoid robot walking",
    "h1hand-stand-customized-v0": "a humanoid robot standing",
    "h1hand-walk-customized-v0": "a humanoid robot walking",
    "h1hand-balance_simple-customized-v0": "a humanoid robot balancing on the board",
    "h1hand-sit_simple-customized-v0": "a humanoid robot sitting on a chair",
}
TASKS_TARGET = {
    "h1hand-run-customized-v0": 700,
    "h1hand-sit_hard-customized-v0": 750,
    "h1hand-powerlift-customized-v0": 800,
    "h1hand-balance_hard-customized-v0": 800,
    "h1hand-crawl-customized-v0": 700,
    "h1hand-push-customized-v0": 700,
    "h1hand-reach-customized-v0": 12000,
    "CustomizedHumanoid-v4": 7000,
    "h1hand_basketball-customized-v0": 1200,
    "h1hand-cabinet-customized-v0": 2500.,
    "h1hand-slide-customized-v0": 700,
    "h1hand-stand-customized-v0": 800,
    "h1hand-walk-customized-v0": 700,
    "h1hand-balance_simple-customized-v0": 800,
    "h1hand-sit_simple-customized-v0": 750,
    "h1hand-stair-customized-v0": 700,
}
